-- SCRUM-379 — Particionamento de `readings` por mês, gerenciado por pg_partman.
--
-- MIGRAÇÃO COM MOVIMENTAÇÃO DE DADOS. Exige janela de manutenção e backup.
-- Racional e números medidos em docs/otimizacoes.md.
--
-- Por que pg_partman e não uma função caseira:
--   A criação de partição é a única parte deste desenho que falha em SILÊNCIO.
--   Se ninguém criar a partição do mês que vem, o INSERT não quebra — a leitura
--   cai na partição DEFAULT e o ganho de pruning some sem erro nenhum. Delegar
--   isso a uma extensão madura, com `premake` criando meses à frente, troca uma
--   falha silenciosa por uma folga de 4 meses.
--
-- Por que pg_partman e não TimescaleDB:
--   No Neon só a edição Apache-2 da TimescaleDB está disponível — sem retention
--   policy, sem continuous aggregate e sem compressão. Além disso, hypertable
--   sobre coluna inteira só aceita chunk de N segundos fixos (30 dias), enquanto
--   `p_epoch => 'seconds'` do pg_partman dá mês de calendário de verdade sobre o
--   mesmo `bigint`. Ver docs/otimizacoes.md, seção 7.
--
-- Dois efeitos colaterais a conhecer antes de aplicar:
--   1. A PK vira composta `(id, unix_time)` — o Postgres exige a chave de
--      partição na PRIMARY KEY.
--   2. Por causa de (1), a FK triggered_alerts.reading_id -> readings(id)
--      deixa de ser possível e é removida na etapa 7.

BEGIN;

-- 0. Guardas -----------------------------------------------------------------

-- Reaplicar a 010 sobre um banco já migrado falharia lá na etapa 2 com um erro
-- confuso ("readings_old já existe"). Melhor dizer o que aconteceu.
DO $$
BEGIN
  IF (SELECT relkind FROM pg_class
       WHERE relname = 'readings' AND relnamespace = 'public'::regnamespace) = 'p' THEN
    RAISE EXCEPTION 'readings já está particionada — a 010 já foi aplicada neste banco.';
  END IF;
END;
$$;

-- As fronteiras de mês que o create_parent calcula viram a arquitetura
-- permanente das partições. Se a sessão que aplica a migration estiver em outro
-- fuso, elas nascem deslocadas em relação ao mês em UTC — e não há como
-- corrigir depois sem remigrar.
SET LOCAL TimeZone = 'UTC';

-- 1. Extensão ----------------------------------------------------------------

-- pg_partman mora em schema próprio, por recomendação da própria extensão.
CREATE SCHEMA IF NOT EXISTS partman;
CREATE EXTENSION IF NOT EXISTS pg_partman SCHEMA partman;

-- Falha cedo e com mensagem clara em banco que não tenha a extensão, em vez de
-- estourar lá embaixo no create_parent.
DO $$
BEGIN
  IF to_regprocedure('partman.create_parent(text,text,text,text,text,integer,text,boolean,text,text,text[],text,boolean,text,text)') IS NULL
     AND NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_partman') THEN
    RAISE EXCEPTION
      'pg_partman não está disponível neste banco. No Neon: CREATE EXTENSION pg_partman SCHEMA partman; em Docker local use a imagem que já traz a extensão.';
  END IF;
END;
$$;

-- 2. Aposenta a tabela atual -------------------------------------------------

-- Os objetos dependentes precisam ser renomeados junto: constraint e índice
-- ocupam o mesmo namespace e colidiriam com os nomes da tabela nova.
ALTER TABLE readings RENAME TO readings_old;
ALTER TABLE readings_old RENAME CONSTRAINT readings_pk TO readings_old_pk;
ALTER TABLE readings_old RENAME CONSTRAINT readings_sensor_fk TO readings_old_sensor_fk;
ALTER INDEX IF EXISTS idx_readings_sensor_time RENAME TO idx_readings_old_sensor_time;
ALTER INDEX IF EXISTS idx_readings_time RENAME TO idx_readings_old_time;

-- RENAME TO da tabela NÃO renomeia a sequence da coluna IDENTITY. Sem esta
-- linha, `readings_id_seq` continua pertencendo à readings_old e o Postgres
-- cria silenciosamente uma `readings_id_seq1` para a tabela nova — sem erro,
-- mas com o nome errado para sempre, e qualquer GRANT por nome deixa de valer.
ALTER SEQUENCE IF EXISTS readings_id_seq RENAME TO readings_old_id_seq;

-- 3. Tabela particionada -----------------------------------------------------

CREATE TABLE readings (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  sensor_id integer NOT NULL,
  value decimal(10,2) NOT NULL,
  unix_time bigint NOT NULL,
  data_consistent boolean NOT NULL DEFAULT true,
  created_at timestamp NOT NULL DEFAULT current_timestamp,
  CONSTRAINT readings_pk PRIMARY KEY (id, unix_time),
  -- A FK para sensors é mantida: desde o PG12 uma tabela particionada pode ser
  -- o lado que referencia. É a FK para `readings` (etapa 7) que se perde, não
  -- esta.
  CONSTRAINT readings_sensor_fk FOREIGN KEY (sensor_id) REFERENCES sensors (id) ON DELETE CASCADE
) PARTITION BY RANGE (unix_time);

-- Índice declarado no pai: o Postgres propaga sozinho para toda partição nova,
-- inclusive as que o pg_partman criar daqui pra frente.
CREATE INDEX idx_readings_sensor_time ON readings (sensor_id, unix_time DESC);

-- 4. Template de storage parameters ------------------------------------------

-- O Postgres recusa storage parameters em tabela particionada, e por isso eles
-- não podem ser declarados no pai. O pg_partman resolve com uma tabela
-- template: o que estiver nela é replicado em cada partição criada.
--   fillfactor 100 -> readings é append-only, não há HOT update a acomodar.
--   autovacuum por gatilho absoluto -> o padrão de 20% da tabela é longe demais
--   em partição com milhões de linhas, e estatística velha gera plano ruim.
CREATE TABLE IF NOT EXISTS partman.template_public_readings (LIKE public.readings);

ALTER TABLE partman.template_public_readings SET (
  fillfactor = 100,
  autovacuum_vacuum_scale_factor = 0.01,
  autovacuum_vacuum_threshold = 10000,
  autovacuum_analyze_scale_factor = 0.005,
  autovacuum_analyze_threshold = 5000
);

-- 5. Registro no pg_partman --------------------------------------------------

-- p_epoch => 'seconds' é o que faz o pg_partman entender que `unix_time` é
-- epoch em segundos e ainda assim fatiar por mês de calendário.
-- p_premake => 4 cria 4 meses à frente: se a manutenção mensal falhar, há 4
-- meses de folga antes de qualquer leitura cair na DEFAULT.
-- p_start_partition recua até a leitura mais antiga, senão o histórico inteiro
-- cairia na DEFAULT ao ser copiado na etapa 6.
DO $$
DECLARE
  first_month timestamptz;
  menor       bigint;
  maior       bigint;
BEGIN
  SELECT MIN(unix_time), MAX(unix_time) INTO menor, maior FROM readings_old;

  -- Uma única linha com timestamp em MILISSEGUNDOS (ou negativo) distorce o
  -- MIN/MAX e faria o create_parent gerar milhares de partições a partir de
  -- uma data absurda. Melhor abortar e limpar o dado antes.
  IF menor IS NOT NULL THEN
    IF menor < 1262304000 THEN   -- 2010-01-01
      RAISE EXCEPTION
        'unix_time mínimo (%) é anterior a 2010. Suspeita de valor negativo ou de unidade errada; limpe o dado antes de particionar.', menor;
    END IF;
    IF maior > extract(epoch FROM now() + interval '1 year')::bigint THEN
      RAISE EXCEPTION
        'unix_time máximo (%) está a mais de um ano no futuro. Suspeita de timestamp em milissegundos; limpe o dado antes de particionar.', maior;
    END IF;
  END IF;

  SELECT COALESCE(date_trunc('month', to_timestamp(MIN(unix_time))), date_trunc('month', now()))
  INTO first_month
  FROM readings_old;

  PERFORM partman.create_parent(
    p_parent_table    => 'public.readings',
    p_control         => 'unix_time',
    p_interval        => '1 month',
    p_epoch           => 'seconds',
    p_premake         => 4,
    p_start_partition => to_char(first_month, 'YYYY-MM-DD HH24:MI:SS'),
    p_default_table   => true
  );
END;
$$;

-- Retenção: 24 meses, com DROP da partição (não DELETE).
-- O expurgo só acontece quando a manutenção roda — ver 012.
UPDATE partman.part_config
SET retention = '24 months',
    retention_keep_table = false,
    infinite_time_partitions = true
WHERE parent_table = 'public.readings';

-- 6. Cópia dos dados ---------------------------------------------------------

INSERT INTO readings
  (id, sensor_id, value, unix_time, data_consistent, created_at)
SELECT id, sensor_id, value, unix_time, data_consistent, created_at
FROM readings_old;

-- is_called = false quando a tabela está vazia, para não queimar o id 1.
SELECT setval(
  pg_get_serial_sequence('readings', 'id'),
  GREATEST((SELECT COALESCE(MAX(id), 1) FROM readings), 1),
  (SELECT EXISTS (SELECT 1 FROM readings))
);

-- Validação da cópia, ainda DENTRO da transação: qualquer divergência aqui
-- reverte tudo. Sem este bloco, uma cópia parcial ou linhas caindo na DEFAULT
-- passariam pelo COMMIT e só seriam notadas muito depois, pelo job da 012.
DO $$
DECLARE
  antes   bigint;
  depois  bigint;
  na_default bigint := 0;
BEGIN
  SELECT count(*) INTO antes  FROM readings_old;
  SELECT count(*) INTO depois FROM readings;

  IF antes <> depois THEN
    RAISE EXCEPTION 'Cópia divergente: % linhas em readings_old, % em readings.', antes, depois;
  END IF;

  IF to_regclass('public.readings_default') IS NOT NULL THEN
    EXECUTE 'SELECT count(*) FROM public.readings_default' INTO na_default;
    IF na_default > 0 THEN
      RAISE EXCEPTION
        'A cópia deixou % linha(s) na partição DEFAULT — as faixas criadas não cobrem todo o histórico.', na_default;
    END IF;
  END IF;

  RAISE NOTICE 'Cópia validada: % linhas, nenhuma na DEFAULT.', depois;
END;
$$;

-- 7. FK de triggered_alerts --------------------------------------------------

-- A alternativa seria carregar unix_time em triggered_alerts e usar FK
-- composta; descartada para não encarecer o caminho quente da ingestão.
-- A integridade passa a ser da aplicação: o motor de regras só grava alerta
-- a partir de uma leitura que acabou de ler.
ALTER TABLE triggered_alerts DROP CONSTRAINT IF EXISTS FK_11;
ALTER TABLE triggered_alerts DROP CONSTRAINT IF EXISTS triggered_alerts_reading_fk;

CREATE INDEX IF NOT EXISTS idx_triggered_alerts_reading_id
  ON triggered_alerts (reading_id);

ANALYZE readings;

COMMIT;

-- Depois de validar em produção: DROP TABLE readings_old;
