-- =============================================================================
-- Schema completo da plataforma AgroClima 360 — aplicação no Neon
--
--   psql "<DATABASE_URL>" -v ON_ERROR_STOP=1 -f setup/schema-neon.sql
--
-- Idempotente: pode rodar quantas vezes quiser, não apaga nem altera dado
-- existente. Segue o modelo oficial do projeto (CONTEXTO/Modelo Banco - SQL),
-- com dois acréscimos necessários aos serviços:
--   - processing_checkpoints  (motor de regras, SCRUM-373)
--   - índices de apoio das consultas quentes
--
-- NÃO aplica as otimizações da SCRUM-379 (migrations 010-012). Aquelas movem
-- dados e exigem janela de manutenção — ver docs/otimizacoes.md.
-- =============================================================================

-- Cargos ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS roles (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name varchar(50) NOT NULL,
  description varchar(255) NULL,
  created_at timestamp NOT NULL DEFAULT current_timestamp,
  CONSTRAINT roles_pk PRIMARY KEY (id),
  CONSTRAINT roles_name_unique UNIQUE (name)
);

-- Usuários -------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  role_id integer NOT NULL,
  name varchar(150) NOT NULL,
  active boolean NOT NULL DEFAULT true,
  created_at timestamp NOT NULL DEFAULT current_timestamp,
  CONSTRAINT users_pk PRIMARY KEY (id),
  CONSTRAINT users_role_fk FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_users_role_id ON users (role_id);

-- Credenciais ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS credentials (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  user_id integer NOT NULL,
  email varchar(150) NOT NULL,
  password_hash varchar(255) NOT NULL,
  updated_at timestamp NOT NULL DEFAULT current_timestamp,
  CONSTRAINT credentials_pk PRIMARY KEY (id),
  CONSTRAINT credentials_email_unique UNIQUE (email),
  CONSTRAINT credentials_user_unique UNIQUE (user_id),
  CONSTRAINT credentials_user_fk FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- Propriedades ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS properties (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name varchar(100) NOT NULL,
  owner_user_id integer NOT NULL,
  location varchar(255) NULL,
  created_at timestamp NOT NULL DEFAULT current_timestamp,
  CONSTRAINT properties_pk PRIMARY KEY (id),
  CONSTRAINT properties_owner_fk FOREIGN KEY (owner_user_id) REFERENCES users (id) ON DELETE RESTRICT
);

-- Estações (SCRUM-359 / SCRUM-360) -------------------------------------------
CREATE TABLE IF NOT EXISTS stations (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  property_id integer NOT NULL,
  mac_address varchar(50) NOT NULL,
  name varchar(100) NOT NULL,
  latitude decimal(10,8) NULL,
  longitude decimal(11,8) NULL,
  last_communication_at timestamp NULL,
  created_at timestamp NOT NULL DEFAULT current_timestamp,
  CONSTRAINT stations_pk PRIMARY KEY (id),
  CONSTRAINT stations_mac_address_unique UNIQUE (mac_address),
  CONSTRAINT stations_property_fk FOREIGN KEY (property_id) REFERENCES properties (id) ON DELETE CASCADE
);

-- Listagem filtrada: GET /stations?property_id=
CREATE INDEX IF NOT EXISTS idx_stations_property_id ON stations (property_id);

-- Tipos de sensor ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sensor_types (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name varchar(50) NOT NULL,
  unit_of_measure varchar(20) NOT NULL,
  factor decimal(10,2) NULL,
  gain decimal(10,2) NULL,
  CONSTRAINT sensor_types_pk PRIMARY KEY (id),
  CONSTRAINT sensor_types_name_unique UNIQUE (name)
);

-- Sensores -------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sensors (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  station_id integer NOT NULL,
  sensor_type_id integer NOT NULL,
  local_identifier varchar(50) NOT NULL,
  operational_status boolean NOT NULL DEFAULT true,
  created_at timestamp NOT NULL DEFAULT current_timestamp,
  CONSTRAINT sensors_pk PRIMARY KEY (id),
  CONSTRAINT sensors_station_identifier_unique UNIQUE (station_id, local_identifier),
  CONSTRAINT sensors_station_fk FOREIGN KEY (station_id) REFERENCES stations (id) ON DELETE CASCADE,
  CONSTRAINT sensors_type_fk FOREIGN KEY (sensor_type_id) REFERENCES sensor_types (id) ON DELETE RESTRICT
);

-- Leituras -------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS readings (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  sensor_id integer NOT NULL,
  value decimal(10,2) NOT NULL,
  unix_time bigint NOT NULL,
  data_consistent boolean NOT NULL DEFAULT true,
  created_at timestamp NOT NULL DEFAULT current_timestamp,
  CONSTRAINT readings_pk PRIMARY KEY (id),
  CONSTRAINT readings_sensor_fk FOREIGN KEY (sensor_id) REFERENCES sensors (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_readings_sensor_time ON readings (sensor_id ASC, unix_time DESC);
CREATE INDEX IF NOT EXISTS idx_readings_time ON readings (unix_time DESC);

-- Configurações de alerta (SCRUM-374) ----------------------------------------
CREATE TABLE IF NOT EXISTS alert_configs (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  manager_user_id integer NULL,
  sensor_id integer NOT NULL,
  reference_value decimal(8,2) NOT NULL,
  comparison_operator varchar(2) NOT NULL,
  message varchar(200) NULL,
  active boolean NOT NULL DEFAULT true,
  created_at timestamp NOT NULL DEFAULT current_timestamp,
  CONSTRAINT alert_configs_pk PRIMARY KEY (id),
  CONSTRAINT alert_configs_comparison_operator_check
    CHECK (comparison_operator IN ('>', '<', '>=', '<=', '=', '!=')),
  CONSTRAINT alert_configs_manager_fk FOREIGN KEY (manager_user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT alert_configs_sensors FOREIGN KEY (sensor_id) REFERENCES sensors (id)
);

-- Alertas disparados ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS triggered_alerts (
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  alert_config_id integer NOT NULL,
  reading_id bigint NOT NULL,
  acknowledged_by integer NULL,
  triggered_at timestamp NOT NULL DEFAULT current_timestamp,
  acknowledged_at timestamp NULL,
  CONSTRAINT triggered_alerts_pk PRIMARY KEY (id),
  CONSTRAINT triggered_alerts_config_fk FOREIGN KEY (alert_config_id) REFERENCES alert_configs (id) ON DELETE CASCADE,
  CONSTRAINT triggered_alerts_reading_fk FOREIGN KEY (reading_id) REFERENCES readings (id) ON DELETE CASCADE,
  CONSTRAINT triggered_alerts_ack_fk FOREIGN KEY (acknowledged_by) REFERENCES users (id) ON DELETE SET NULL
);

-- Motor de regras (SCRUM-373) ------------------------------------------------

-- Guarda o último reading_id avaliado, para o motor reiniciar sem reprocessar
-- a base inteira nem pular leituras.
CREATE TABLE IF NOT EXISTS processing_checkpoints (
  key varchar(100) NOT NULL,
  value varchar(100) NOT NULL,
  updated_at timestamp NOT NULL DEFAULT current_timestamp,
  CONSTRAINT processing_checkpoints_pk PRIMARY KEY (key)
);

INSERT INTO processing_checkpoints (key, value)
VALUES ('rules_engine_last_reading_id', '0')
ON CONFLICT (key) DO NOTHING;

-- Impede que o mesmo par (leitura, regra) gere dois alertas. É o que torna
-- seguro reprocessar um lote após falha.
CREATE UNIQUE INDEX IF NOT EXISTS uq_triggered_alerts_reading_config
  ON triggered_alerts (reading_id, alert_config_id);

-- Consulta executada a cada ciclo do motor.
CREATE INDEX IF NOT EXISTS idx_alert_configs_sensor_active
  ON alert_configs (sensor_id) WHERE active = true;

-- Listagem de alertas pendentes no portal.
CREATE INDEX IF NOT EXISTS idx_triggered_alerts_pending
  ON triggered_alerts (triggered_at DESC) WHERE acknowledged_at IS NULL;
